services:
  db:
    image: postgres:18-alpine
    container_name: testingDB
    restart: always
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
      POSTGRES_DB: ${POSTGRES_DB_NAME:?error}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis_test
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:?error}
    volumes:
      - cache:/data

volumes:
  postgres_data:
  cache:
